#!/usr/bin/env bash
bash -n "$0" | exit 1

pgrep cdb2sockpool
if [ $? -ne 0 ]; then
    echo 'SOCKPOOL IS REQUIRED TO RUN THE TEST BUT IS NOT RUNNING.' >&2
    echo 'TRYING TO BRING IT UP'
    ${BUILDDIR}/tools/cdb2sockpool/cdb2sockpool
    sleep 1
    pgrep cdb2sockpool
    if [ $? -ne 0 ]; then
        echo 'FAILED BRINGING UP SOCKPOOL' >&2
        exit 1
    fi
fi


${TESTSBUILDDIR}/cdb2api_localcache_systable ${DBNAME}
[[ $? -ne 0 ]] && echo "cdb2api_localcache_systable - fail" && exit 1
echo 'cdb2api_localcache_systable - pass'

exit 0